[package]
name = "ash_destructor"
version = "0.0.1"
edition = "2021"

[[test]]
name = "tests"
path = "tests/ui_tests.rs"

[dev-dependencies]
trybuild = { version = "1.0.101", features = ["diff"] }

[dependencies]
ash_destructor_derive = { path = "derive" }
ash = "0.38.0"

